# Generated by Django 3.2 on 2024-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obfuscated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMDOS', models.CharField(max_length=255)),
                ('NUMDOSVERLING', models.CharField(max_length=255)),
                ('ANCART', models.CharField(max_length=255)),
                ('FILIERE', models.CharField(max_length=255)),
                ('ETAPE', models.CharField(max_length=255)),
                ('VERLING', models.CharField(max_length=255)),
                ('FORMAT', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Obfuscated',
                'verbose_name_plural': 'Obfuscateds',
                'ordering': ('id',),
            },
        ),
    ]
